---

- name: install elasticsearch and dependencies
  package:
    name:
      - java-1.8.0-openjdk
      - elasticsearch
    state: present

- name: install ingest-attachment plugin for elasticsearch
  elasticsearch_plugin:
    name: ingest-attachment
    state: present
  notify: restart elasticsearch
  tags:
    - elasticsearch

- name: increase the virtual memory map limit
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present

- name: start elasticsearch
  service:
    name: elasticsearch
    state: started
  tags:
    - elasticsearch

- name: enable elasticsearch
  service:
    name: elasticsearch
    enabled: yes
  tags:
    - elasticsearch

...
