---

- name: ensuring elasticsearch is started
  service:
    name: elasticsearch
    state: started
  tags:
    - elasticsearch

- name: install ingest-attachment plugin for elasticsearch
  elasticsearch_plugin:
    name: ingest-attachment
    state: present
  notify: restart elasticsearch
  tags:
    - elasticsearch

...
