---
- name: install elasticsearch and dependencies
  package:
    name:
      - java-1.8.0-openjdk.x86_64
      - elasticsearch
    state: present

- name: install zammad
  package:
    name: zammad
    state: present

- name: add nginx user to nginx group
  user:
    name: nginx
    groups: nginx
    append: yes

...
